# Generated by Django 3.0.5 on 2020-05-09 23:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_post', '0003_auto_20200509_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 23, 47, 30, 840826, tzinfo=utc)),
        ),
    ]
